# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/tariffication_db
spring.datasource.username=tarif_user
spring.datasource.password=tarif_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Application settings
google.sheets.url=https://docs.google.com/spreadsheets/d/1_2XDnInfHUKfj8jrzyU7EtzQz9G2oUTRZ-ALz1cePfU/export?format=xlsx
download.file.name=???????? 1 ????????? ?????????????
output.file.path=C:\\Users\\dimah\\Desktop\\???????????.xlsx

# Scheduling (??????????? - ??? ??????????????? ???????)
spring.task.scheduling.pool.size=1