spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tariffication_db}
    username: ${DB_USERNAME:tarif_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO

app:
  sheets-url: ${TARIFFICATION_SHEETS_URL:https://docs.google.com/spreadsheets/d/1yDBzOWy7ReQ7vhFFCQN6F58wichu9FAVgrl688uNykI/export?format=xlsx}
  tariffication-file-prefix: ${TARIFFICATION_FILE_PREFIX:Нагрузка 2 полугодие}
  practicum-file-name: ${PRACTICUM_FILE_NAME:ЕГЭ 2026 автоскачанный}
  download-directory: ${DOWNLOAD_DIRECTORY:./data/downloads/}
  output-directory: ${OUTPUT_DIRECTORY:./data/output/}
  offline-files-directory: ${OFFLINE_FILES_DIRECTORY:./data/offline/}
  expelled-file-path: ${EXPELLED_FILE_PATH:./data/expelled.xlsx}
  keep-history: ${KEEP_HISTORY:true}
  clear-history-on-start: ${CLEAR_HISTORY_ON_START:false}
  excluded-teachers:
    - "Сухомлинова Вера Борисовна"

mail:
  smtp-host: ${SMTP_HOST:smtp.gmail.com}
  smtp-port: ${SMTP_PORT:587}
  username: ${SMTP_USERNAME}
  password: ${SMTP_PASSWORD}
  use-ssl: ${SMTP_USE_SSL:false}
  use-tls: ${SMTP_USE_TLS:true}
  default-recipients: ${SMTP_DEFAULT_RECIPIENTS:recipient1@example.com,recipient2@example.com}
  default-subject: ${SMTP_DEFAULT_SUBJECT:Тарификация - автоматическая отправка}
