spring:
  servlet:
    multipart:
      max-file-size: ${MAX_UPLOAD_FILE_SIZE:30MB}
      max-request-size: ${MAX_UPLOAD_REQUEST_SIZE:35MB}
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
          no-store: true
          must-revalidate: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tariffication_db}
    username: ${DB_USERNAME:tarif_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.school.personalLoad.service.impl.ServiceMemoServiceImpl: DEBUG

app:
  output-directory: ${OUTPUT_DIRECTORY:./data/output/}
  keep-history: ${KEEP_HISTORY:true}
  clear-history-on-start: ${CLEAR_HISTORY_ON_START:false}
  excluded-teachers:
    - "Сухомлинова Вера Борисовна"
  security:
    default-admin:
      username: ${APP_ADMIN_USERNAME:admin}
      password: ${APP_ADMIN_PASSWORD:admin}
      full-name: ${APP_ADMIN_FULL_NAME:Главный администратор}

mail:
  smtp-host: ${SMTP_HOST:smtp.gmail.com}
  smtp-port: ${SMTP_PORT:587}
  username: ${SMTP_USERNAME}
  password: ${SMTP_PASSWORD}
  use-ssl: ${SMTP_USE_SSL:false}
  use-tls: ${SMTP_USE_TLS:true}
  default-recipients: ${SMTP_DEFAULT_RECIPIENTS:recipient1@example.com,recipient2@example.com}
  default-subject: ${SMTP_DEFAULT_SUBJECT:Тарификация - автоматическая отправка}
