package org.school.personalLoad.service.impl;

import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class HrDocumentsFrontendTest {
    @Test
    void pageContainsReworkedMemoAndPersonalDataControls() throws Exception {
        String html = Files.readString(Path.of("src/main/resources/static/teachers-notification.html"));
        String js = Files.readString(Path.of("src/main/resources/static/teachers-notification.js"));
        String controller = Files.readString(Path.of("src/main/java/org/school/personalLoad/controller/api/HrDocumentsController.java"));

        assertTrue(html.contains("Предварительная нагрузка (уведомления)"));
        assertTrue(html.contains("Импортировать Excel"));
        assertTrue(html.indexOf("data-tab=\"journal\"") < html.indexOf("data-tab=\"memos\""));
        assertTrue(html.indexOf("data-tab=\"memos\"") < html.indexOf("data-tab=\"agreements\""));
        assertTrue(html.contains("data-tab=\"journal\" class=\"active\""));
        assertTrue(html.contains(".hr-tabs button.active"));
        assertTrue(html.contains("personal-body"));
        assertTrue(html.contains("Данные хранятся на сервере"));
        assertTrue(html.contains("hr-form-grid"));
        assertTrue(js.contains("Обязанность из справочника"));
        assertTrue(js.contains("Добавить вручную"));
        assertTrue(js.contains("STANDARD_CONTRACT_CLAUSES = ['2.1','2.4','2.5']"));
        assertTrue(js.contains("'2.1':'2.1 — учебная нагрузка'"));
        assertTrue(js.contains("'2.4':'2.4 — дополнительные функции'"));
        assertTrue(js.contains("'2.5':'2.5 — стимулирующие выплаты'"));
        assertTrue(js.contains("Проверить или изменить автоматический текст"));
        assertTrue(js.contains("система всегда собирает утверждённую полную редакцию"));
        assertTrue(js.contains("Пока нет договора — служебка всё равно сформируется"));
        assertTrue(js.contains("ожидает договор"));
        assertTrue(js.contains("Promise.allSettled"));
        assertTrue(js.contains("Не удалось загрузить список работников"));
        assertTrue(js.contains("loadTeachersForDocuments"));
        assertTrue(js.contains("api('/api/teachers')"));
        assertTrue(html.contains("teachers-notification.js?v=20260727-3"));
        assertTrue(js.contains("const automaticClause24=clause==='2.4'&&!item.separateAgreement"));
        assertTrue(js.contains("$('#memo-text').value=automaticClause24?'':item.memoText||''"));
        assertTrue(js.contains("memoText:automaticClause24?null:form.get('memo')"));
        assertTrue(js.contains("Служебная записка создана и добавлена в таблицу"));
        assertTrue(js.contains("await loadMemos()"));
        assertTrue(html.contains("Дополнительные соглашения"));
        assertTrue(js.contains("/api/hr-documents/agreements?academicYear="));
        assertTrue(js.contains("data-delete-catalog"));
        assertTrue(js.contains("data-delete-memo"));
        assertTrue(js.contains("Нет — изменить выбранный пункт"));
        assertTrue(js.contains("Да — отдельное соглашение"));
        assertTrue(js.contains("data-issue-memo"));
        assertTrue(js.contains("Ожидает служебку"));
        assertTrue(js.contains("/api/hr-documents/load-memos"));
        assertTrue(js.contains("Способ изменения"));
        assertTrue(js.contains("CATEGORY_LABELS"));
        assertTrue(js.contains("personal-data/import"));
        assertTrue(js.contains("data-reject"));
        assertTrue(js.contains("data-delete-agreement"));
        assertTrue(js.contains("data-merge-agreements"));
        assertTrue(js.contains("data-merge-reissue"));
        assertTrue(js.contains("/api/hr-documents/agreements/merge"));
        assertTrue(js.contains("Объединить и перевыпустить"));
        assertTrue(js.contains("data-reopen-agreement"));
        assertTrue(js.contains("/reopen"));
        assertTrue(js.contains("Исправить и перевыпустить"));
        assertTrue(js.contains("agreement.reissueRequired"));
        assertTrue(js.contains("В документ добавлены новые пункты"));
        assertTrue(js.contains("DOCX (старая версия)"));
        assertTrue(html.contains("<option>Перевыпустить</option>"));
        assertFalse(js.contains("ПЕРЕВЫПУСТИТЬ"));
        assertTrue(js.contains("классное руководство (пункт 2.4)"));
        assertTrue(js.contains("введите слово УДАЛИТЬ"));
        assertTrue(js.contains("json('DELETE',{confirmation,reason:reason.trim()})"));
        assertTrue(controller.contains("\"УДАЛИТЬ\".equals(r.confirmation())"));
        assertTrue(controller.contains("\"DELETE_CONFIRMED\""));
        assertTrue(controller.contains("\"REISSUE_MERGE\""));
        assertTrue(controller.contains("\"REOPEN_FOR_REISSUE\""));
        assertTrue(controller.contains("причина: "));
        assertTrue(html.contains("Сводный контроль по работникам"));
        assertTrue(html.contains("Рабочий список кадров"));
        assertTrue(html.contains("id=\"all-agreements\""));
        assertTrue(html.contains("Все допники"));
        assertTrue(html.contains("id=\"all-agreements-dialog\""));
        assertTrue(html.contains("id=\"memo-archive\""));
        assertTrue(html.contains("Архив служебных записок"));
        assertTrue(html.contains("Обновить список"));
        assertTrue(js.contains("Документы не создавались и не изменялись"));
        assertTrue(js.contains("data-sign-memo"));
        assertTrue(js.contains("data-sign-load-memo"));
        assertTrue(js.contains("data-receive-memo"));
        assertTrue(js.contains("editIssuedMemo"));
        assertTrue(js.contains("возвращена в черновик"));
        assertTrue(js.contains("/memos/archive?academicYear="));
        assertTrue(js.contains("/load-memos/archive?academicYear="));
        assertTrue(html.contains("Сформировать на 1 сентября"));
        assertTrue(js.contains("Не заполнен"));
        assertTrue(js.contains("data-edit-agreement"));
        assertTrue(js.contains("'ISSUED','SIGNING'].includes(agreement.status)"));
        assertTrue(js.contains("Сформировать DOCX"));
        assertTrue(js.contains("Заполнить договор"));
        assertTrue(js.contains("Сохранить как шаблон"));
        assertTrue(js.contains("Автоматический текст сформирован по образцу допсоглашения школы"));
        assertTrue(js.contains("/prepare"));
        assertTrue(js.contains("loadPersonalData"));
        assertTrue(js.contains("api('/api/hr-documents/personal-data')"));
        assertTrue(js.contains("из служебной записки"));
        assertTrue(js.contains("Дополнительное соглашение вне служебной записки"));
        assertTrue(html.contains("data-tab=\"incentives\""));
        assertTrue(html.contains("id=\"incentive-body\""));
        assertTrue(html.contains("Стимул, руб."));
        assertTrue(js.contains("/api/hr-documents/incentives?academicYear="));
        assertTrue(js.contains("/api/hr-documents/incentives/import?academicYear="));
        assertTrue(js.contains("data-save-incentive"));
        assertTrue(!js.contains("ID полученной служебки"));
    }
}
